[package]
name = "stonk-vault"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "=2.2.0"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[features]
no-entrypoint = []
custom-heap = []
custom-panic = []
